import Home from "./Home";
import Konsul from "./Konsul";
import BlogDetail from "./BlogDetail";
import Profile from "./Profile";
import AddBlogForm from "./AddBlogForm";
import EditBlogForm from "./EditBlogForm";
import Login from "./Login";
import Register from "./Register";
import SplashScreen from "./SplashScreen";
export {Home, Konsul, Profile,BlogDetail,AddBlogForm,EditBlogForm,SplashScreen,Register,Login}